In [1]:
import pandas as pd

In [2]:
questionDF = pd.read_csv('Question-bank-KTLT.csv', sep=';')
reportsDF = pd.read_csv('new_reports.csv', sep=';', dtype={'ID number': str, 'questionID': str})

In [3]:
questionDF

,Lab,Pre/In/Post,question,question name,topic,level,"bkel-link,"
0,1,Prelab,1.20,[Q 1.2] Đảo ngược các ký tự trong chuỗi,C-string,1-easy,https://e-learning-old.hcmut.edu.vn/mod/quiz/v...
1,1,Prelab,1.10,[Q 1.1] Loại bỏ các khoảng trắng thừa,C-string,2-medium,https://e-learning-old.hcmut.edu.vn/mod/quiz/v...
2,1,Prelab,1.50,[Q 1.5] Tính giá trị của một chuỗi bit nhị phân,C-string,2-medium,https://e-learning-old.hcmut.edu.vn/mod/quiz/v...
3,1,Prelab,2.70,[Q 2.7] In ra một phần của chuỗi,Class string,1-easy,https://e-learning-old.hcmut.edu.vn/mod/quiz/v...
4,1,Prelab,2.60,[Q 2.6] Tìm tất cả vị trí xuất hiện của chuỗi ...,Class string,1-easy,https://e-learning-old.hcmut.edu.vn/mod/quiz/v...
...,...,...,...,...,...,...,...
94,4,Postlab,1.16,[Q 1.16] class CoordinateQuiz,OOP,2-medium,https://e-learning-old.hcmut.edu.vn/mod/quiz/v...
95,4,Prelab,1.17,[Q 1.17] class CourseQuiz,OOP,3-hard,https://e-learning-old.hcmut.edu.vn/mod/quiz/v...
96,4,Inlab,1.12,[Q 1.12] Integer: Constructor & operator+Quiz,OOP,3-hard,https://e-learning-old.hcmut.edu.vn/mod/quiz/v...
97,4,Inlab,1.15,[Q 1.15] class Array: Copy Constructor & Copy ...,OOP,3-hard,https://e-learning-old.hcmut.edu.vn/mod/quiz/v...
98,4,Postlab,1.18,[Q 1.18] class Array2DQuiz,OOP,3-hard,https://e-learning-old.hcmut.edu.vn/mod/quiz/v...

In [4]:
reportsDF

,Surname,First name,ID number,State,Started on,Completed,Time taken,Grade/10.00,Q. 1 /10.00,questionID
0,Huy,Nguyễn Quốc,2113519,Finished,21 January 2022 5:45 PM,21 January 2022 8:28 PM,2 hours 43 mins,6.36,6.36,788089
1,Huy,Lê Đăng Phan,2110196,Finished,21 January 2022 5:55 PM,21 January 2022 6:33 PM,37 mins 33 secs,0.00,0.00,788089
2,Nam,Vũ Nhật,1911660,Finished,21 January 2022 5:57 PM,21 January 2022 6:13 PM,16 mins 7 secs,10.00,10.00,788089
3,Kiên,Đoàn Hồng Hiếu,2052555,Finished,21 January 2022 5:59 PM,21 January 2022 7:24 PM,1 hour 24 mins,10.00,10.00,788089
4,Huy,La Cẩm,2153379,Finished,21 January 2022 6:16 PM,21 January 2022 6:24 PM,8 mins 18 secs,10.00,10.00,788089
...,...,...,...,...,...,...,...,...,...,...
67075,Huy,Nguyễn Công,2113499,Finished,30 April 2022 3:55 AM,30 April 2022 3:56 AM,25 secs,10.00,10.00,810006
67076,Khoa,Lương Anh,2011421,Finished,1 May 2022 12:11 PM,1 May 2022 12:49 PM,37 mins 33 secs,10.00,10.00,810006
67077,Bách,Trần Trọng,2112847,Finished,1 May 2022 3:20 PM,1 May 2022 3:25 PM,4 mins 16 secs,10.00,10.00,810006
67078,Trung,Trần Việt,2120075,Finished,2 May 2022 10:29 AM,2 May 2022 3:41 PM,5 hours 11 mins,10.00,10.00,810006
67079,Khanh,Ngô Ngọc,1913720,Finished,2 May 2022 3:42 PM,2 May 2022 3:45 PM,3 mins 21 secs,10.00,10.00,810006

In [10]:

# Concatenate Firstname and Surname
reportsDF['Fullname'] = reportsDF['First name'] + ' ' + reportsDF['Surname']

# Print the result
print(reportsDF[['Fullname', 'ID number', 'State', 'Started on', 'Completed', 'Time taken', 'Grade/10.00', 'Q. 1 /10.00', 'questionID']])

                  Fullname ID number     State                Started on  \
0          Nguyễn Quốc Huy   2113519  Finished  21 January 2022  5:45 PM
1         Lê Đăng Phan Huy   2110196  Finished  21 January 2022  5:55 PM
2              Vũ Nhật Nam   1911660  Finished  21 January 2022  5:57 PM
3      Đoàn Hồng Hiếu Kiên   2052555  Finished  21 January 2022  5:59 PM
4               La Cẩm Huy   2153379  Finished  21 January 2022  6:16 PM
...                    ...       ...       ...                       ...
67075      Nguyễn Công Huy   2113499  Finished    30 April 2022  3:55 AM
67076       Lương Anh Khoa   2011421  Finished      1 May 2022  12:11 PM
67077      Trần Trọng Bách   2112847  Finished       1 May 2022  3:20 PM
67078      Trần Việt Trung   2120075  Finished      2 May 2022  10:29 AM
67079       Ngô Ngọc Khanh   1913720  Finished       2 May 2022  3:42 PM

                      Completed       Time taken  Grade/10.00  Q. 1 /10.00  \
0      21 January 2022  8:28 PM  2 hours 43 mins         6.36         6.36
1      21 January 2022  6:33 PM  37 mins 33 secs         0.00         0.00
2      21 January 2022  6:13 PM   16 mins 7 secs        10.00        10.00
3      21 January 2022  7:24 PM   1 hour 24 mins        10.00        10.00
4      21 January 2022  6:24 PM   8 mins 18 secs        10.00        10.00
...                         ...              ...          ...          ...
67075    30 April 2022  3:56 AM          25 secs        10.00        10.00
67076      1 May 2022  12:49 PM  37 mins 33 secs        10.00        10.00
67077       1 May 2022  3:25 PM   4 mins 16 secs        10.00        10.00
67078       2 May 2022  3:41 PM  5 hours 11 mins        10.00        10.00
67079       2 May 2022  3:45 PM   3 mins 21 secs        10.00        10.00

      questionID
0         788089
1         788089
2         788089
3         788089
4         788089
...          ...
67075     810006
67076     810006
67077     810006
67078     810006
67079     810006

[67080 rows x 9 columns]

In [11]:
reportsDF

,Surname,First name,ID number,State,Started on,Completed,Time taken,Grade/10.00,Q. 1 /10.00,questionID,Fullname
0,Huy,Nguyễn Quốc,2113519,Finished,21 January 2022 5:45 PM,21 January 2022 8:28 PM,2 hours 43 mins,6.36,6.36,788089,Nguyễn Quốc Huy
1,Huy,Lê Đăng Phan,2110196,Finished,21 January 2022 5:55 PM,21 January 2022 6:33 PM,37 mins 33 secs,0.00,0.00,788089,Lê Đăng Phan Huy
2,Nam,Vũ Nhật,1911660,Finished,21 January 2022 5:57 PM,21 January 2022 6:13 PM,16 mins 7 secs,10.00,10.00,788089,Vũ Nhật Nam
3,Kiên,Đoàn Hồng Hiếu,2052555,Finished,21 January 2022 5:59 PM,21 January 2022 7:24 PM,1 hour 24 mins,10.00,10.00,788089,Đoàn Hồng Hiếu Kiên
4,Huy,La Cẩm,2153379,Finished,21 January 2022 6:16 PM,21 January 2022 6:24 PM,8 mins 18 secs,10.00,10.00,788089,La Cẩm Huy
...,...,...,...,...,...,...,...,...,...,...,...
67075,Huy,Nguyễn Công,2113499,Finished,30 April 2022 3:55 AM,30 April 2022 3:56 AM,25 secs,10.00,10.00,810006,Nguyễn Công Huy
67076,Khoa,Lương Anh,2011421,Finished,1 May 2022 12:11 PM,1 May 2022 12:49 PM,37 mins 33 secs,10.00,10.00,810006,Lương Anh Khoa
67077,Bách,Trần Trọng,2112847,Finished,1 May 2022 3:20 PM,1 May 2022 3:25 PM,4 mins 16 secs,10.00,10.00,810006,Trần Trọng Bách
67078,Trung,Trần Việt,2120075,Finished,2 May 2022 10:29 AM,2 May 2022 3:41 PM,5 hours 11 mins,10.00,10.00,810006,Trần Việt Trung
67079,Khanh,Ngô Ngọc,1913720,Finished,2 May 2022 3:42 PM,2 May 2022 3:45 PM,3 mins 21 secs,10.00,10.00,810006,Ngô Ngọc Khanh

In [16]:
reportsDF

,ID number,State,Started on,Completed,Time taken,Grade/10.00,Q. 1 /10.00,questionID,Fullname
0,2113519,Finished,21 January 2022 5:45 PM,21 January 2022 8:28 PM,2 hours 43 mins,6.36,6.36,788089,Nguyễn Quốc Huy
1,2110196,Finished,21 January 2022 5:55 PM,21 January 2022 6:33 PM,37 mins 33 secs,0.00,0.00,788089,Lê Đăng Phan Huy
2,1911660,Finished,21 January 2022 5:57 PM,21 January 2022 6:13 PM,16 mins 7 secs,10.00,10.00,788089,Vũ Nhật Nam
3,2052555,Finished,21 January 2022 5:59 PM,21 January 2022 7:24 PM,1 hour 24 mins,10.00,10.00,788089,Đoàn Hồng Hiếu Kiên
4,2153379,Finished,21 January 2022 6:16 PM,21 January 2022 6:24 PM,8 mins 18 secs,10.00,10.00,788089,La Cẩm Huy
...,...,...,...,...,...,...,...,...,...
67075,2113499,Finished,30 April 2022 3:55 AM,30 April 2022 3:56 AM,25 secs,10.00,10.00,810006,Nguyễn Công Huy
67076,2011421,Finished,1 May 2022 12:11 PM,1 May 2022 12:49 PM,37 mins 33 secs,10.00,10.00,810006,Lương Anh Khoa
67077,2112847,Finished,1 May 2022 3:20 PM,1 May 2022 3:25 PM,4 mins 16 secs,10.00,10.00,810006,Trần Trọng Bách
67078,2120075,Finished,2 May 2022 10:29 AM,2 May 2022 3:41 PM,5 hours 11 mins,10.00,10.00,810006,Trần Việt Trung
67079,1913720,Finished,2 May 2022 3:42 PM,2 May 2022 3:45 PM,3 mins 21 secs,10.00,10.00,810006,Ngô Ngọc Khanh

In [24]:
cols = reportsDF.columns.tolist()
cols.remove('ID number')
cols.append('ID number')
reportsDF = reportsDF[cols]
reportsDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67080 entries, 0 to 67079
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   State        67080 non-null  object
 1   Started on   67080 non-null  object
 2   Completed    67080 non-null  object
 3   Time taken   67080 non-null  object
 4   Grade/10.00  67080 non-null  float64
 5   Q. 1 /10.00  67080 non-null  float64
 6   questionID   67080 non-null  object
 7   Fullname     67080 non-null  object
 8   ID number    67080 non-null  object
dtypes: float64(2), object(7)
memory usage: 4.6+ MB

In [25]:
import hashlib

# Hàm để hash giá trị trong cột
def hash_column_value(value):
    # Sử dụng SHA-256 để hash giá trị
    hashed_value = hashlib.sha256(value.encode()).hexdigest()
    return hashed_value

# Áp dụng hàm hash_column_value cho cột "Fullname"
reportsDF['Fullname'] = reportsDF['Fullname'].apply(hash_column_value)

# Áp dụng hàm hash_column_value cho cột "ID number"
reportsDF['ID number'] = reportsDF['ID number'].apply(hash_column_value)

In [26]:
reportsDF

,State,Started on,Completed,Time taken,Grade/10.00,Q. 1 /10.00,questionID,Fullname,ID number
0,Finished,21 January 2022 5:45 PM,21 January 2022 8:28 PM,2 hours 43 mins,6.36,6.36,788089,9bc0ee837c29052ec029ed1a15ca527a5bec751de10cd0...,fc106703a967b0dfbd4d6707c0cbffe7749a3c9cdbd396...
1,Finished,21 January 2022 5:55 PM,21 January 2022 6:33 PM,37 mins 33 secs,0.00,0.00,788089,8b1d8f657548e0050f4ba16eefdc538a64bb2c36be7bb9...,6fcc31ff44db34ba5823715467db2698ba7eacde1617da...
2,Finished,21 January 2022 5:57 PM,21 January 2022 6:13 PM,16 mins 7 secs,10.00,10.00,788089,879da6ec30af94c63ce0c2f4a5d4bdd86dbd0ed0fb19fb...,e0c4eedfd77f9394e6fa2033d948b6ae620b28f1bac1b5...
3,Finished,21 January 2022 5:59 PM,21 January 2022 7:24 PM,1 hour 24 mins,10.00,10.00,788089,4d9d799c94555e8f67b848a5dbd73f39567a681c9057b4...,135a2466ddf69075337514210f82cba85ac9b5b30b2334...
4,Finished,21 January 2022 6:16 PM,21 January 2022 6:24 PM,8 mins 18 secs,10.00,10.00,788089,f9361a3791487ef9676ba1c008ae4bff02c43ee19853a1...,7cf229d119f36daa477ac16e624f04f72e11f81fed1b14...
...,...,...,...,...,...,...,...,...,...
67075,Finished,30 April 2022 3:55 AM,30 April 2022 3:56 AM,25 secs,10.00,10.00,810006,23dbf3fa67316976f5efe61c586717c4d7cfbbbb787abb...,f626b85266a338f4e908aec40c0294d88d11da3290a62a...
67076,Finished,1 May 2022 12:11 PM,1 May 2022 12:49 PM,37 mins 33 secs,10.00,10.00,810006,6387ee190bcf99dc89071b3cc94ed1be4b14fd1250c48f...,15c5471ce240f13c80b836cf8fb444eeec94f9009165a2...
67077,Finished,1 May 2022 3:20 PM,1 May 2022 3:25 PM,4 mins 16 secs,10.00,10.00,810006,d39f6cd52a1ee8ceb9a024787e5b10ce5c30bea66d5990...,3bbc699e1976effeef4e6547605596bd24e434fb590911...
67078,Finished,2 May 2022 10:29 AM,2 May 2022 3:41 PM,5 hours 11 mins,10.00,10.00,810006,1995377292fed54056d9c7b41a6bc7f10e31adeac3531a...,168158c29303cb21585ac8c298a50facc3f50b1cb7eab8...
67079,Finished,2 May 2022 3:42 PM,2 May 2022 3:45 PM,3 mins 21 secs,10.00,10.00,810006,ffbb1caa420cf06023727b1d565e45c98cb4825ffa40c8...,cc72993cc3ade3987027bd249d55839de76e13a380fb61...

In [27]:
# Xuất DataFrame ra file CSV
reportsDF.to_csv('reports.csv', index=False)

In [28]:
questionDF

,Lab,Pre/In/Post,question,question name,topic,level,"bkel-link,"
0,1,Prelab,1.20,[Q 1.2] Đảo ngược các ký tự trong chuỗi,C-string,1-easy,https://e-learning-old.hcmut.edu.vn/mod/quiz/v...
1,1,Prelab,1.10,[Q 1.1] Loại bỏ các khoảng trắng thừa,C-string,2-medium,https://e-learning-old.hcmut.edu.vn/mod/quiz/v...
2,1,Prelab,1.50,[Q 1.5] Tính giá trị của một chuỗi bit nhị phân,C-string,2-medium,https://e-learning-old.hcmut.edu.vn/mod/quiz/v...
3,1,Prelab,2.70,[Q 2.7] In ra một phần của chuỗi,Class string,1-easy,https://e-learning-old.hcmut.edu.vn/mod/quiz/v...
4,1,Prelab,2.60,[Q 2.6] Tìm tất cả vị trí xuất hiện của chuỗi ...,Class string,1-easy,https://e-learning-old.hcmut.edu.vn/mod/quiz/v...
...,...,...,...,...,...,...,...
94,4,Postlab,1.16,[Q 1.16] class CoordinateQuiz,OOP,2-medium,https://e-learning-old.hcmut.edu.vn/mod/quiz/v...
95,4,Prelab,1.17,[Q 1.17] class CourseQuiz,OOP,3-hard,https://e-learning-old.hcmut.edu.vn/mod/quiz/v...
96,4,Inlab,1.12,[Q 1.12] Integer: Constructor & operator+Quiz,OOP,3-hard,https://e-learning-old.hcmut.edu.vn/mod/quiz/v...
97,4,Inlab,1.15,[Q 1.15] class Array: Copy Constructor & Copy ...,OOP,3-hard,https://e-learning-old.hcmut.edu.vn/mod/quiz/v...
98,4,Postlab,1.18,[Q 1.18] class Array2DQuiz,OOP,3-hard,https://e-learning-old.hcmut.edu.vn/mod/quiz/v...

In [29]:
reportsDF

,State,Started on,Completed,Time taken,Grade/10.00,Q. 1 /10.00,questionID,Fullname,ID number
0,Finished,21 January 2022 5:45 PM,21 January 2022 8:28 PM,2 hours 43 mins,6.36,6.36,788089,9bc0ee837c29052ec029ed1a15ca527a5bec751de10cd0...,fc106703a967b0dfbd4d6707c0cbffe7749a3c9cdbd396...
1,Finished,21 January 2022 5:55 PM,21 January 2022 6:33 PM,37 mins 33 secs,0.00,0.00,788089,8b1d8f657548e0050f4ba16eefdc538a64bb2c36be7bb9...,6fcc31ff44db34ba5823715467db2698ba7eacde1617da...
2,Finished,21 January 2022 5:57 PM,21 January 2022 6:13 PM,16 mins 7 secs,10.00,10.00,788089,879da6ec30af94c63ce0c2f4a5d4bdd86dbd0ed0fb19fb...,e0c4eedfd77f9394e6fa2033d948b6ae620b28f1bac1b5...
3,Finished,21 January 2022 5:59 PM,21 January 2022 7:24 PM,1 hour 24 mins,10.00,10.00,788089,4d9d799c94555e8f67b848a5dbd73f39567a681c9057b4...,135a2466ddf69075337514210f82cba85ac9b5b30b2334...
4,Finished,21 January 2022 6:16 PM,21 January 2022 6:24 PM,8 mins 18 secs,10.00,10.00,788089,f9361a3791487ef9676ba1c008ae4bff02c43ee19853a1...,7cf229d119f36daa477ac16e624f04f72e11f81fed1b14...
...,...,...,...,...,...,...,...,...,...
67075,Finished,30 April 2022 3:55 AM,30 April 2022 3:56 AM,25 secs,10.00,10.00,810006,23dbf3fa67316976f5efe61c586717c4d7cfbbbb787abb...,f626b85266a338f4e908aec40c0294d88d11da3290a62a...
67076,Finished,1 May 2022 12:11 PM,1 May 2022 12:49 PM,37 mins 33 secs,10.00,10.00,810006,6387ee190bcf99dc89071b3cc94ed1be4b14fd1250c48f...,15c5471ce240f13c80b836cf8fb444eeec94f9009165a2...
67077,Finished,1 May 2022 3:20 PM,1 May 2022 3:25 PM,4 mins 16 secs,10.00,10.00,810006,d39f6cd52a1ee8ceb9a024787e5b10ce5c30bea66d5990...,3bbc699e1976effeef4e6547605596bd24e434fb590911...
67078,Finished,2 May 2022 10:29 AM,2 May 2022 3:41 PM,5 hours 11 mins,10.00,10.00,810006,1995377292fed54056d9c7b41a6bc7f10e31adeac3531a...,168158c29303cb21585ac8c298a50facc3f50b1cb7eab8...
67079,Finished,2 May 2022 3:42 PM,2 May 2022 3:45 PM,3 mins 21 secs,10.00,10.00,810006,ffbb1caa420cf06023727b1d565e45c98cb4825ffa40c8...,cc72993cc3ade3987027bd249d55839de76e13a380fb61...